name: "Nix Flake Check"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Flake Check
        run: nix flake check

      - name: Home Manager Evaluation
        run: nix build .#homeConfigurations.matthewdehaas.activationPackage
